on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Testing GitHub Action'
        run: pwd

      - name: 'Testing Printing'
        run: echo Hamza
