name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        run: pwd
      - name: 'Testing Printing'
        run: echo Hamza
