on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Testing GitHub Action'
        uses: pwd

      - name: 'Testing Printing'
        run: echo Hamza